// SPDX-License-Identifier: MPL-2.0

//! Threaded background image preparation for [`super::ImageContainer`].
//!
//! This pipeline moves expensive image decode + optional blur work to worker
//! threads, supports in-process memory cache, and can persist prepared images
//! to disk so later launches can reuse them.

use super::blur_image;

use cosmic::iced::core::image;
use image_crate::imageops::FilterType;
use std::{
    collections::{HashMap, HashSet, hash_map::DefaultHasher},
    fs,
    hash::{Hash, Hasher},
    io::{self, Read, Write},
    path::{Path, PathBuf},
    sync::{Arc, Mutex, mpsc},
    thread,
    time::{Duration, SystemTime, UNIX_EPOCH},
};

const CACHE_SCHEMA_VERSION: u32 = 1;
const RAW_CACHE_MAGIC: [u8; 8] = *b"COSIMG1\0";

/// A fully prepared image pair for an [`ImageContainer`].
#[derive(Debug, Clone)]
pub struct PreparedImage {
    /// Original image (already decoded / resized).
    pub original: image::Handle,
    /// Optional pre-blurred variant.
    pub blurred: Option<image::Handle>,
}

/// Stable cache key for a prepared request.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct PreparedImageCacheKey(u64);

impl PreparedImageCacheKey {
    /// Raw numeric key (useful for logging/debugging).
    pub fn as_u64(self) -> u64 {
        self.0
    }
}

/// Where a prepared result came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PreparedImageSource {
    /// Returned from in-process memory cache.
    MemoryCache,
    /// Loaded from persistent on-disk cache.
    DiskCache,
    /// Freshly decoded/generated by worker threads.
    WorkerGenerated,
}

/// Request describing how a source image should be prepared.
#[derive(Debug, Clone)]
pub struct PreparedImageRequest {
    path: PathBuf,
    max_dimension: u32,
    blur_sigma: Option<f32>,
}

impl PreparedImageRequest {
    /// Create a request for a source image path.
    pub fn new(path: impl Into<PathBuf>) -> Self {
        Self {
            path: path.into(),
            max_dimension: 1600,
            blur_sigma: None,
        }
    }

    /// Set the maximum decoded dimension before upload.
    pub fn max_dimension(mut self, max_dimension: u32) -> Self {
        self.max_dimension = max_dimension.max(1);
        self
    }

    /// Request a blurred variant (`None` or non-positive = disabled).
    pub fn blur_sigma(mut self, sigma: f32) -> Self {
        self.blur_sigma = if sigma > 0.0 { Some(sigma) } else { None };
        self
    }

    /// Source path for this request.
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Max decoded dimension for this request.
    pub fn max_dimension_value(&self) -> u32 {
        self.max_dimension
    }

    /// Requested blur sigma.
    pub fn blur_sigma_value(&self) -> Option<f32> {
        self.blur_sigma
    }
}

/// Event emitted by the threaded pipeline.
#[derive(Debug, Clone)]
pub enum PreparedImageEvent {
    /// Preparation succeeded.
    Ready {
        key: PreparedImageCacheKey,
        request: PreparedImageRequest,
        image: PreparedImage,
        source: PreparedImageSource,
    },
    /// Preparation failed.
    Failed {
        key: PreparedImageCacheKey,
        request: PreparedImageRequest,
        error: String,
    },
}

/// Config for [`ThreadedImagePipeline`].
#[derive(Debug, Clone)]
pub struct ThreadedImagePipelineConfig {
    /// Number of worker threads used for decode/blur.
    pub worker_threads: usize,
    /// Whether persistent disk cache should be used.
    pub disk_cache_enabled: bool,
    /// Optional custom disk cache directory.
    pub disk_cache_dir: Option<PathBuf>,
    /// Soft upper bound of cache files kept on disk.
    pub disk_cache_max_files: usize,
}

impl Default for ThreadedImagePipelineConfig {
    fn default() -> Self {
        Self {
            worker_threads: 2,
            disk_cache_enabled: true,
            disk_cache_dir: None,
            disk_cache_max_files: 256,
        }
    }
}

/// Background worker pipeline for preparing image assets.
#[derive(Clone)]
pub struct ThreadedImagePipeline {
    inner: Arc<PipelineInner>,
}

struct PipelineInner {
    job_tx: mpsc::Sender<WorkerCommand>,
    ready_tx: mpsc::Sender<PreparedImageEvent>,
    ready_rx: Mutex<mpsc::Receiver<PreparedImageEvent>>,
    memory_cache: Arc<Mutex<HashMap<PreparedImageCacheKey, PreparedImage>>>,
    in_flight: Arc<Mutex<HashSet<PreparedImageCacheKey>>>,
}

enum WorkerCommand {
    Prepare {
        key: PreparedImageCacheKey,
        request: PreparedImageRequest,
    },
}

impl ThreadedImagePipeline {
    /// Create a new threaded image pipeline.
    pub fn new(config: ThreadedImagePipelineConfig) -> Self {
        let (job_tx, job_rx) = mpsc::channel::<WorkerCommand>();
        let (ready_tx, ready_rx) = mpsc::channel::<PreparedImageEvent>();

        let memory_cache = Arc::new(Mutex::new(HashMap::new()));
        let in_flight = Arc::new(Mutex::new(HashSet::new()));

        let job_rx = Arc::new(Mutex::new(job_rx));
        let disk_cache = DiskCache::new(&config);

        let worker_count = config.worker_threads.max(1);
        for idx in 0..worker_count {
            let job_rx = Arc::clone(&job_rx);
            let ready_tx = ready_tx.clone();
            let memory_cache = Arc::clone(&memory_cache);
            let in_flight = Arc::clone(&in_flight);
            let disk_cache = disk_cache.clone();

            let _ = thread::Builder::new()
                .name(format!("cosmetics-image-loader-{idx}"))
                .spawn(move || {
                    worker_loop(job_rx, ready_tx, memory_cache, in_flight, disk_cache);
                });
        }

        Self {
            inner: Arc::new(PipelineInner {
                job_tx,
                ready_tx,
                ready_rx: Mutex::new(ready_rx),
                memory_cache,
                in_flight,
            }),
        }
    }

    /// Queue a request, returning its cache key.
    ///
    /// If the request is already in memory cache, a `Ready` event is pushed to
    /// the ready queue immediately.
    pub fn request(&self, request: PreparedImageRequest) -> PreparedImageCacheKey {
        let key = cache_key_for_request(&request);

        if let Some(cached) = self
            .inner
            .memory_cache
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .get(&key)
            .cloned()
        {
            let _ = self.inner.ready_tx.send(PreparedImageEvent::Ready {
                key,
                request,
                image: cached,
                source: PreparedImageSource::MemoryCache,
            });
            return key;
        }

        {
            let mut in_flight = self
                .inner
                .in_flight
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner());
            if !in_flight.insert(key) {
                return key;
            }
        }

        if self
            .inner
            .job_tx
            .send(WorkerCommand::Prepare {
                key,
                request: request.clone(),
            })
            .is_err()
        {
            self.inner
                .in_flight
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner())
                .remove(&key);
            let _ = self.inner.ready_tx.send(PreparedImageEvent::Failed {
                key,
                request,
                error: "background worker channel closed".to_string(),
            });
        }

        key
    }

    /// Get a prepared image from memory cache if available.
    pub fn cached(&self, key: PreparedImageCacheKey) -> Option<PreparedImage> {
        self.inner
            .memory_cache
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .get(&key)
            .cloned()
    }

    /// Block until the next event is available.
    pub fn wait_next(&self) -> Option<PreparedImageEvent> {
        self.inner
            .ready_rx
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .recv()
            .ok()
    }

    /// Block until the next event arrives or timeout elapses.
    pub fn wait_next_timeout(&self, timeout: Duration) -> Option<PreparedImageEvent> {
        self.inner
            .ready_rx
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .recv_timeout(timeout)
            .ok()
    }

    /// Non-blocking event drain.
    pub fn try_next(&self) -> Option<PreparedImageEvent> {
        self.inner
            .ready_rx
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .try_recv()
            .ok()
    }
}

fn worker_loop(
    job_rx: Arc<Mutex<mpsc::Receiver<WorkerCommand>>>,
    ready_tx: mpsc::Sender<PreparedImageEvent>,
    memory_cache: Arc<Mutex<HashMap<PreparedImageCacheKey, PreparedImage>>>,
    in_flight: Arc<Mutex<HashSet<PreparedImageCacheKey>>>,
    disk_cache: DiskCache,
) {
    loop {
        let command = job_rx
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .recv();

        let WorkerCommand::Prepare { key, request } = match command {
            Ok(command) => command,
            Err(_) => break,
        };

        if let Some(cached) = disk_cache.read(key) {
            memory_cache
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner())
                .insert(key, cached.clone());
            in_flight
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner())
                .remove(&key);
            let _ = ready_tx.send(PreparedImageEvent::Ready {
                key,
                request,
                image: cached,
                source: PreparedImageSource::DiskCache,
            });
            continue;
        }

        match prepare_image(&request) {
            Ok(prepared) => {
                memory_cache
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .insert(key, prepared.clone());
                disk_cache.write(key, &prepared);

                in_flight
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .remove(&key);
                let _ = ready_tx.send(PreparedImageEvent::Ready {
                    key,
                    request,
                    image: prepared,
                    source: PreparedImageSource::WorkerGenerated,
                });
            }
            Err(error) => {
                in_flight
                    .lock()
                    .unwrap_or_else(|poisoned| poisoned.into_inner())
                    .remove(&key);
                let _ = ready_tx.send(PreparedImageEvent::Failed {
                    key,
                    request,
                    error,
                });
            }
        }
    }
}

fn prepare_image(request: &PreparedImageRequest) -> Result<PreparedImage, String> {
    let (width, height, pixels) = decode_and_resize(&request.path, request.max_dimension)?;

    let original = image::Handle::from_rgba(width, height, pixels);
    let blurred = request.blur_sigma.and_then(|sigma| {
        if sigma > 0.0 {
            blur_image(&original, sigma)
        } else {
            None
        }
    });

    Ok(PreparedImage { original, blurred })
}

fn decode_and_resize(path: &Path, max_dimension: u32) -> Result<(u32, u32, Vec<u8>), String> {
    let mut rgba = image_crate::ImageReader::open(path)
        .map_err(|err| format!("failed to open {}: {err}", path.display()))?
        .decode()
        .map_err(|err| format!("failed to decode {}: {err}", path.display()))?
        .into_rgba8();

    let (w, h) = rgba.dimensions();

    if max_dimension > 0 && w.max(h) > max_dimension {
        let scale = max_dimension as f32 / w.max(h) as f32;
        let target_w = ((w as f32 * scale).round() as u32).max(1);
        let target_h = ((h as f32 * scale).round() as u32).max(1);
        rgba = image_crate::imageops::resize(&rgba, target_w, target_h, FilterType::Triangle);
    }

    let (w, h) = rgba.dimensions();
    Ok((w, h, rgba.into_raw()))
}

fn cache_key_for_request(request: &PreparedImageRequest) -> PreparedImageCacheKey {
    let canonical_path = fs::canonicalize(&request.path).unwrap_or_else(|_| request.path.clone());
    let metadata = fs::metadata(&canonical_path).ok();

    let mut hasher = DefaultHasher::new();

    CACHE_SCHEMA_VERSION.hash(&mut hasher);
    canonical_path.to_string_lossy().hash(&mut hasher);
    request.max_dimension.hash(&mut hasher);
    request.blur_sigma.map(f32::to_bits).hash(&mut hasher);

    if let Some(metadata) = metadata {
        metadata.len().hash(&mut hasher);

        if let Ok(modified) = metadata.modified()
            && let Ok(elapsed) = modified.duration_since(UNIX_EPOCH)
        {
            elapsed.as_secs().hash(&mut hasher);
            elapsed.subsec_nanos().hash(&mut hasher);
        }
    }

    PreparedImageCacheKey(hasher.finish())
}

#[derive(Clone)]
struct DiskCache {
    root: Option<PathBuf>,
    max_files: usize,
}

impl DiskCache {
    fn new(config: &ThreadedImagePipelineConfig) -> Self {
        if !config.disk_cache_enabled {
            return Self {
                root: None,
                max_files: config.disk_cache_max_files.max(16),
            };
        }

        let root = config
            .disk_cache_dir
            .clone()
            .or_else(default_cache_root)
            .map(|root| {
                root.join("image_container")
                    .join(format!("v{CACHE_SCHEMA_VERSION}"))
            });

        if let Some(root) = &root {
            let _ = fs::create_dir_all(root);
        }

        Self {
            root,
            max_files: config.disk_cache_max_files.max(16),
        }
    }

    fn read(&self, key: PreparedImageCacheKey) -> Option<PreparedImage> {
        let original_path = self.original_path(key)?;
        let (w, h, original_pixels) = read_raw_rgba(&original_path).ok()?;

        let blurred = self
            .blur_path(key)
            .and_then(|path| read_raw_rgba(&path).ok())
            .map(|(bw, bh, pixels)| image::Handle::from_rgba(bw, bh, pixels));

        Some(PreparedImage {
            original: image::Handle::from_rgba(w, h, original_pixels),
            blurred,
        })
    }

    fn write(&self, key: PreparedImageCacheKey, prepared: &PreparedImage) {
        let Some(original_path) = self.original_path(key) else {
            return;
        };

        let Some((w, h, pixels)) = handle_to_raw(&prepared.original) else {
            return;
        };

        let _ = write_raw_rgba_atomic(&original_path, w, h, &pixels);

        if let Some(blur_path) = self.blur_path(key) {
            if let Some(blurred) = &prepared.blurred {
                if let Some((bw, bh, bpixels)) = handle_to_raw(blurred) {
                    let _ = write_raw_rgba_atomic(&blur_path, bw, bh, &bpixels);
                }
            } else {
                let _ = fs::remove_file(blur_path);
            }
        }

        self.prune();
    }

    fn prune(&self) {
        let Some(root) = &self.root else {
            return;
        };

        let mut entries = match fs::read_dir(root) {
            Ok(entries) => entries
                .filter_map(Result::ok)
                .filter_map(|entry| {
                    let path = entry.path();
                    if !path.is_file() {
                        return None;
                    }

                    let modified = entry
                        .metadata()
                        .ok()
                        .and_then(|meta| meta.modified().ok())
                        .and_then(|m| m.duration_since(UNIX_EPOCH).ok())
                        .unwrap_or(Duration::ZERO);

                    Some((modified, path))
                })
                .collect::<Vec<_>>(),
            Err(_) => return,
        };

        if entries.len() <= self.max_files {
            return;
        }

        entries.sort_by_key(|(modified, _)| *modified);
        let remove_count = entries.len().saturating_sub(self.max_files);

        for (_, path) in entries.into_iter().take(remove_count) {
            let _ = fs::remove_file(path);
        }
    }

    fn original_path(&self, key: PreparedImageCacheKey) -> Option<PathBuf> {
        self.root
            .as_ref()
            .map(|root| root.join(format!("{:016x}.orig.rgba", key.0)))
    }

    fn blur_path(&self, key: PreparedImageCacheKey) -> Option<PathBuf> {
        self.root
            .as_ref()
            .map(|root| root.join(format!("{:016x}.blur.rgba", key.0)))
    }
}

fn default_cache_root() -> Option<PathBuf> {
    if let Some(xdg_cache_home) = std::env::var_os("XDG_CACHE_HOME") {
        return Some(PathBuf::from(xdg_cache_home).join("cosmetics"));
    }

    std::env::var_os("HOME").map(|home| PathBuf::from(home).join(".cache").join("cosmetics"))
}

fn handle_to_raw(handle: &image::Handle) -> Option<(u32, u32, Vec<u8>)> {
    match handle {
        image::Handle::Rgba {
            width,
            height,
            pixels,
            ..
        } => Some((*width, *height, pixels.to_vec())),
        _ => None,
    }
}

fn read_raw_rgba(path: &Path) -> io::Result<(u32, u32, Vec<u8>)> {
    let mut file = fs::File::open(path)?;

    let mut magic = [0u8; RAW_CACHE_MAGIC.len()];
    file.read_exact(&mut magic)?;

    if magic != RAW_CACHE_MAGIC {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "unexpected cache file magic",
        ));
    }

    let width = read_u32_le(&mut file)?;
    let height = read_u32_le(&mut file)?;
    let len = read_u64_le(&mut file)? as usize;

    let expected = width as usize * height as usize * 4;
    if len != expected {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "cached buffer length mismatch",
        ));
    }

    let mut pixels = vec![0u8; len];
    file.read_exact(&mut pixels)?;

    Ok((width, height, pixels))
}

fn write_raw_rgba_atomic(path: &Path, width: u32, height: u32, pixels: &[u8]) -> io::Result<()> {
    let expected = width as usize * height as usize * 4;
    if pixels.len() != expected {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "pixel length does not match width*height*4",
        ));
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or(Duration::ZERO)
        .as_nanos();
    let tmp = path.with_extension(format!("tmp-{nonce}"));

    {
        let mut file = fs::File::create(&tmp)?;
        file.write_all(&RAW_CACHE_MAGIC)?;
        file.write_all(&width.to_le_bytes())?;
        file.write_all(&height.to_le_bytes())?;
        file.write_all(&(pixels.len() as u64).to_le_bytes())?;
        file.write_all(pixels)?;
        file.flush()?;
    }

    fs::rename(tmp, path)?;
    Ok(())
}

fn read_u32_le(reader: &mut impl Read) -> io::Result<u32> {
    let mut bytes = [0u8; 4];
    reader.read_exact(&mut bytes)?;
    Ok(u32::from_le_bytes(bytes))
}

fn read_u64_le(reader: &mut impl Read) -> io::Result<u64> {
    let mut bytes = [0u8; 8];
    reader.read_exact(&mut bytes)?;
    Ok(u64::from_le_bytes(bytes))
}
